### ISSUE TITLE
Deprecation warning in PHP8

### ISSUE THREAD

**Issue by Whip** [RobThree/TwoFactorAuth#89]
On PHP8, this warning is displayed when generating secret and QR code

```
Deprecated: rawurlencode(): Passing null to parameter #1 ($string) of type string is deprecated in ProjectFolder\vendor\robthree\twofactorauth\lib\TwoFactorAuth.php on line 275
```

**Comment by willpower232** [comment]
We've had this fixed in master, but I was trying to wait for #84 before releasing. I'll try and get it finished and released today.

**Comment by Whip** [comment]
Composer is still not picking up this version. Is this normal? I'm running `composer update`. The version I have is 1.8.

**Comment by willpower232** [comment]
1.8.1 is showing up in packagist https://packagist.org/packages/robthree/twofactorauth

do you need to do `composer require robthree/twofactorauth ^1.8.1` ?

**Comment by Whip** [comment]
That worked. Thanks

**Comment by willpower232** [comment]
good to know, unfortunately `composer update` needs a helping hand sometimes
